"use client";

import { motion } from "motion/react";
import { FileText, UserCheck, ShieldAlert, Briefcase, Server, Brain, Scale, RefreshCw, Mail } from "lucide-react";
import { Navbar } from "@/components/nav/navbar";
import { PageHero } from "@/components/layout/page-hero";
import { SiteFooter } from "@/components/layout/site-footer";
import { ClayPanel } from "@/components/layout/clay-panel";
import { SectionReveal, RevealItem } from "@/components/layout/section-reveal";
import { GlowOrb } from "@/components/effects/glow-orb";

const SECTIONS = [
  {
    icon: FileText,
    color: "#8B5CF6",
    title: "Acceptance of Terms",
    content:
      "By accessing or using BlackCloud, you agree to these Terms of Service. If you are using BlackCloud on behalf of an organization, you represent that you have the authority to bind that organization to these terms.",
  },
  {
    icon: UserCheck,
    color: "#06B6D4",
    title: "Account Responsibilities",
    content:
      "You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account. Notify us immediately at security@blackcloud.dev if you suspect unauthorized access.",
  },
  {
    icon: ShieldAlert,
    color: "#EF4444",
    title: "Acceptable Use",
    content:
      "You may use BlackCloud to design, analyze, simulate, and export cloud infrastructure architectures. You may not use the platform to attack, scan, or exploit real cloud infrastructure without explicit authorization from the resource owner. Automated scraping, credential harvesting, and abuse of AI generation endpoints are prohibited.",
  },
  {
    icon: Briefcase,
    color: "#22C55E",
    title: "Your Content",
    content:
      "You retain ownership of all infrastructure designs, configurations, and data you create on BlackCloud. We claim no intellectual property rights over your content. You grant us a limited license to store, process, and display your content solely to provide the service.",
  },
  {
    icon: Server,
    color: "#F59E0B",
    title: "Service Availability",
    content:
      "We strive for high availability but do not guarantee uninterrupted service. Planned maintenance windows will be announced in advance. We are not liable for damages arising from service downtime.",
  },
  {
    icon: Brain,
    color: "#A78BFA",
    title: "AI-Generated Output",
    content:
      "Architecture designs, cost estimates, security reviews, and Terraform code generated by BlackCloud AI are recommendations, not guarantees. You are responsible for reviewing and validating all AI-generated output before deploying to production environments.",
  },
  {
    icon: Scale,
    color: "#F472B6",
    title: "Limitation of Liability",
    content:
      "BlackCloud is provided 'as is' without warranties of any kind. We are not liable for indirect, incidental, or consequential damages arising from your use of the platform, including but not limited to infrastructure misconfiguration, data loss, or cost overruns.",
  },
  {
    icon: RefreshCw,
    color: "#10B981",
    title: "Changes to Terms",
    content:
      "We may update these terms from time to time. Material changes will be communicated via email and in-app notification at least 30 days before taking effect. Continued use after changes constitutes acceptance.",
  },
  {
    icon: Mail,
    color: "#06B6D4",
    title: "Contact",
    content:
      "Questions about these terms? Contact us at legal@blackcloud.dev or through our contact form.",
  },
];

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="relative min-h-screen bg-void pt-20">
        {/* ambient glow */}
        <GlowOrb color="rgba(6,182,212,0.1)" size={450} className="absolute right-1/4 top-40" />
        <GlowOrb color="rgba(139,92,246,0.08)" size={350} className="absolute left-1/3 top-[70%]" />

        <PageHero
          title="Terms of Service"
          subtitle="Fair terms for everyone"
          badge="Legal"
        />

        <div className="relative mx-auto max-w-3xl px-6 py-16 space-y-6">
          <SectionReveal>
            <p className="text-sm text-muted-foreground">
              Last updated: July 1, 2026
            </p>
          </SectionReveal>

          <SectionReveal stagger={0.1}>
            {SECTIONS.map((s, i) => {
              const Icon = s.icon;
              return (
                <RevealItem key={s.title} delay={i * 0.06}>
                  <motion.div
                    whileHover={{ y: -2 }}
                    transition={{ type: "spring", stiffness: 400, damping: 25 }}
                    className="mb-6"
                  >
                    <ClayPanel hoverable glowColor={s.color} className="p-6">
                      <div className="flex items-start gap-4">
                        <div
                          className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/5"
                          style={{ color: s.color }}
                        >
                          <Icon className="h-5 w-5" />
                        </div>
                        <div>
                          <h2 className="font-display text-lg font-semibold text-foreground">
                            {s.title}
                          </h2>
                          <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                            {s.content}
                          </p>
                        </div>
                      </div>
                    </ClayPanel>
                  </motion.div>
                </RevealItem>
              );
            })}
          </SectionReveal>
        </div>
      </main>
      <SiteFooter />
    </>
  );
}
