"use client";

// AI Architect — prompt-to-architecture console. A clay-inset prompt textarea
// with a prefilled example, a gradient Generate button that runs a mock
// state machine (idle → generating ~1.5s → done, NOT real network), then
// reveals results across four tabs: Diagram, Cost, Terraform, Security.
// Reduced-motion users skip the generating delay entirely.
import { useCallback, useRef, useState } from "react";
import { motion, useReducedMotion } from "motion/react";
import {
  Sparkles,
  CircleDashed,
  CheckCircle2,
  AlertTriangle,
  ShieldCheck,
  ArrowRight,
  Loader2,
} from "lucide-react";
import { AppFrame } from "@/components/layout/app-frame";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { NumberTicker } from "@/components/effects/number-ticker";
import { ServiceIcon, PROVIDER_COLOR } from "@/lib/brand-icons";
import { CATALOG } from "@/lib/catalog/nodes";
import { cn } from "@/lib/utils";

const EXAMPLE_PROMPT =
  "A globally-distributed image-sharing API: authenticated uploads to object storage, " +
  "a serverless resize pipeline, a low-latency metadata store, and a CDN in front. " +
  "Optimize for cost and keep it multi-region.";

// Fixed architecture derived from CATALOG (no randomness in render).
const pick = (id: string) => CATALOG.find((s) => s.id === id)!;
const NODES = [
  { svc: pick("cloudfront"), role: "Edge CDN", col: 0, row: 1 },
  { svc: pick("lambda"), role: "Resize pipeline", col: 1, row: 0 },
  { svc: pick("s3"), role: "Object storage", col: 1, row: 2 },
  { svc: pick("dynamodb"), role: "Metadata store", col: 2, row: 1 },
  { svc: pick("sqs"), role: "Job queue", col: 2, row: 2 },
];
const EDGES: [number, number][] = [
  [0, 1],
  [0, 2],
  [1, 3],
  [1, 4],
  [4, 2],
];

const COST_LINES = [
  { label: "CloudFront — 4 TB egress", monthly: 340 },
  { label: "Lambda — 18M invocations", monthly: 96 },
  { label: "S3 — 2.4 TB standard", monthly: 55 },
  { label: "DynamoDB — on-demand", monthly: 128 },
  { label: "SQS — 40M requests", monthly: 16 },
];
const COST_TOTAL = COST_LINES.reduce((s, l) => s + l.monthly, 0);

const TERRAFORM = `# generated by BlackCloud AI Architect
module "image_api" {
  source  = "blackcloud/image-api/aws"
  version = "1.4.0"

  regions        = ["us-east-1", "eu-west-1"]
  bucket_name    = "bc-images-prod"
  cdn_price_class = "PriceClass_All"

  resize {
    runtime      = "nodejs20"
    memory_mb    = 512
    concurrency  = 200
  }

  metadata {
    engine        = "dynamodb"
    billing_mode  = "PAY_PER_REQUEST"
    global_tables = true
  }
}`;

type SecurityStatus = "pass" | "warn" | "fail";
const SECURITY: { label: string; detail: string; status: SecurityStatus }[] = [
  { label: "Encryption at rest", detail: "S3 + DynamoDB use SSE-KMS", status: "pass" },
  { label: "TLS in transit", detail: "CDN enforces TLS 1.2+", status: "pass" },
  { label: "Least-privilege IAM", detail: "Lambda role scoped to bucket prefix", status: "pass" },
  { label: "Public bucket access", detail: "Block Public Access enabled", status: "pass" },
  { label: "WAF on edge", detail: "No managed rule group attached", status: "warn" },
  { label: "Secrets management", detail: "API keys not yet in Secrets Manager", status: "warn" },
];

const STATUS_STYLE: Record<SecurityStatus, { color: string; Icon: typeof CheckCircle2 }> = {
  pass: { color: "text-status-success", Icon: CheckCircle2 },
  warn: { color: "text-status-warning", Icon: AlertTriangle },
  fail: { color: "text-status-danger", Icon: AlertTriangle },
};

type Phase = "idle" | "generating" | "done";

export default function AiArchitectPage() {
  const reduced = useReducedMotion();
  const [prompt, setPrompt] = useState(EXAMPLE_PROMPT);
  const [phase, setPhase] = useState<Phase>("idle");
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const generate = useCallback(() => {
    if (!prompt.trim()) return;
    if (timer.current) clearTimeout(timer.current);
    if (reduced) {
      setPhase("done");
      return;
    }
    setPhase("generating");
    // ponytail: single setTimeout is the whole "state machine" — no network, no lib.
    timer.current = setTimeout(() => setPhase("done"), 1500);
  }, [prompt, reduced]);

  const confidence = 92;

  return (
    <AppFrame title="AI Architect">
      <div className="mx-auto flex max-w-5xl flex-col gap-6">
        {/* Prompt console */}
        <section className="clay flex flex-col gap-4 rounded-2xl p-5 sm:p-6">
          <div className="flex items-center gap-2">
            <span className="grid size-8 place-items-center rounded-lg bg-gradient-to-br from-accent-violet to-accent-cyan text-white shadow-sm">
              <Sparkles className="size-4" />
            </span>
            <div>
              <h2 className="font-display text-base font-semibold">Describe your system</h2>
              <p className="text-xs text-muted-foreground">
                Plain English in, a deployable multi-cloud architecture out.
              </p>
            </div>
          </div>

          <label htmlFor="ai-prompt" className="sr-only">
            Architecture prompt
          </label>
          <Textarea
            id="ai-prompt"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            rows={4}
            className="min-h-28 resize-none font-mono text-[13px] leading-relaxed"
            placeholder="Describe the system you want to build…"
          />

          <div className="flex flex-wrap items-center justify-between gap-3">
            <p className="text-xs text-muted-foreground">
              Confidence and estimates are illustrative.
            </p>
            <button
              onClick={generate}
              disabled={phase === "generating"}
              className={cn(
                "group inline-flex items-center gap-2 rounded-xl bg-gradient-to-br from-accent-violet to-accent-cyan px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-accent-violet/25 transition-all",
                "hover:shadow-accent-violet/40 focus-visible:ring-2 focus-visible:ring-accent-violet/60 focus-visible:outline-none disabled:opacity-70",
              )}
            >
              {phase === "generating" ? (
                <>
                  <Loader2 className="size-4 animate-spin" /> Generating…
                </>
              ) : (
                <>
                  <Sparkles className="size-4" />
                  {phase === "done" ? "Regenerate" : "Generate"}
                  <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
                </>
              )}
            </button>
          </div>
        </section>

        {/* Generating state */}
        {phase === "generating" && (
          <div
            role="status"
            aria-live="polite"
            className="clay-inset flex flex-col items-center gap-4 rounded-2xl p-10 text-center"
          >
            <motion.div
              className="grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-accent-violet to-accent-cyan text-white"
              animate={{ scale: [1, 1.08, 1], rotate: [0, 6, -6, 0] }}
              transition={{ duration: 1.4, repeat: Infinity, ease: "easeInOut" }}
            >
              <CircleDashed className="size-7 animate-spin" />
            </motion.div>
            <div>
              <p className="font-display text-sm font-medium text-ai">Reasoning about your architecture…</p>
              <p className="mt-1 text-xs text-muted-foreground">
                Selecting services, sizing resources, checking security posture.
              </p>
            </div>
          </div>
        )}

        {/* Results */}
        {phase === "done" && (
          <motion.section
            initial={reduced ? false : { opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="flex flex-col gap-4"
          >
            {/* Confidence indicator */}
            <div className="clay flex flex-wrap items-center gap-4 rounded-2xl p-4">
              <div className="flex items-center gap-2 text-ai">
                <ShieldCheck className="size-5" />
                <span className="font-display text-sm font-semibold">AI confidence</span>
              </div>
              <div className="clay-inset h-2.5 min-w-40 flex-1 overflow-hidden rounded-full">
                <motion.div
                  className="h-full rounded-full bg-gradient-to-r from-accent-violet to-accent-cyan"
                  initial={reduced ? false : { width: 0 }}
                  animate={{ width: `${confidence}%` }}
                  transition={{ duration: 0.8, ease: "easeOut" }}
                />
              </div>
              <span className="font-mono text-sm font-semibold text-ai">{confidence}%</span>
            </div>

            <Tabs defaultValue="diagram" className="clay gap-5 rounded-2xl p-4 sm:p-5">
              <TabsList className="flex-wrap">
                <TabsTrigger value="diagram">Diagram</TabsTrigger>
                <TabsTrigger value="cost">Cost projection</TabsTrigger>
                <TabsTrigger value="terraform">Terraform</TabsTrigger>
                <TabsTrigger value="security">Security review</TabsTrigger>
              </TabsList>

              {/* Diagram */}
              <TabsContent value="diagram">
                <DiagramGraph reduced={!!reduced} />
              </TabsContent>

              {/* Cost */}
              <TabsContent value="cost">
                <div className="clay-inset flex flex-col gap-1 rounded-xl p-4">
                  {COST_LINES.map((line) => (
                    <div
                      key={line.label}
                      className="flex items-center justify-between border-b border-border/40 py-2.5 text-sm last:border-0"
                    >
                      <span className="text-muted-foreground">{line.label}</span>
                      <span className="font-mono font-medium text-foreground">
                        $<NumberTicker value={line.monthly} />
                        <span className="text-muted-foreground">/mo</span>
                      </span>
                    </div>
                  ))}
                  <div className="mt-2 flex items-center justify-between rounded-lg bg-accent-violet/10 px-3 py-3">
                    <span className="font-display text-sm font-semibold">Estimated monthly total</span>
                    <span className="font-mono text-lg font-bold text-ai">
                      $<NumberTicker value={COST_TOTAL} />
                    </span>
                  </div>
                </div>
              </TabsContent>

              {/* Terraform */}
              <TabsContent value="terraform">
                <pre className="clay-inset overflow-x-auto rounded-xl p-4 font-mono text-[13px] leading-relaxed text-foreground/90">
                  <code>{TERRAFORM}</code>
                </pre>
              </TabsContent>

              {/* Security */}
              <TabsContent value="security">
                <ul className="clay-inset flex flex-col gap-1 rounded-xl p-4">
                  {SECURITY.map((item) => {
                    const { color, Icon } = STATUS_STYLE[item.status];
                    return (
                      <li
                        key={item.label}
                        className="flex items-start gap-3 border-b border-border/40 py-2.5 last:border-0"
                      >
                        <Icon className={cn("mt-0.5 size-4 shrink-0", color)} />
                        <div>
                          <p className="text-sm font-medium text-foreground">{item.label}</p>
                          <p className="text-xs text-muted-foreground">{item.detail}</p>
                        </div>
                      </li>
                    );
                  })}
                </ul>
              </TabsContent>
            </Tabs>
          </motion.section>
        )}
      </div>
    </AppFrame>
  );
}

// Stylized node graph laid out on a 3-column grid, SVG edges behind clay nodes.
function DiagramGraph({ reduced }: { reduced: boolean }) {
  const COLS = 3;
  const ROWS = 3;
  const pos = (col: number, row: number) => ({
    x: ((col + 0.5) / COLS) * 100,
    y: ((row + 0.5) / ROWS) * 100,
  });

  return (
    <div className="clay-inset relative aspect-[16/9] w-full overflow-hidden rounded-xl">
      <svg
        className="absolute inset-0 h-full w-full"
        viewBox="0 0 100 100"
        preserveAspectRatio="none"
        aria-hidden
      >
        {EDGES.map(([a, b], i) => {
          const pa = pos(NODES[a].col, NODES[a].row);
          const pb = pos(NODES[b].col, NODES[b].row);
          return (
            <motion.line
              key={i}
              x1={pa.x}
              y1={pa.y}
              x2={pb.x}
              y2={pb.y}
              stroke="var(--accent-violet)"
              strokeWidth={0.4}
              strokeOpacity={0.5}
              vectorEffect="non-scaling-stroke"
              initial={reduced ? false : { pathLength: 0, opacity: 0 }}
              animate={{ pathLength: 1, opacity: 0.5 }}
              transition={{ duration: 0.6, delay: 0.1 * i }}
            />
          );
        })}
      </svg>

      {NODES.map((node, i) => {
        const p = pos(node.col, node.row);
        return (
          <motion.div
            key={node.role}
            className="clay absolute flex -translate-x-1/2 -translate-y-1/2 flex-col items-center gap-1.5 rounded-xl px-3 py-2.5 text-center"
            style={{ left: `${p.x}%`, top: `${p.y}%` }}
            initial={reduced ? false : { opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.35, delay: 0.06 * i }}
          >
            <span
              className="grid size-9 place-items-center rounded-lg"
              style={{ backgroundColor: `color-mix(in oklch, ${PROVIDER_COLOR[node.svc.provider]} 14%, transparent)` }}
            >
              <ServiceIcon provider={node.svc.provider} id={node.svc.id} name={node.svc.name} size={22} />
            </span>
            <span className="text-[11px] font-medium leading-tight text-foreground">{node.role}</span>
          </motion.div>
        );
      })}
    </div>
  );
}
