"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Sparkles,
  Copy,
  Check,
  Clock,
  Layers,
  ShieldCheck,
  ShieldAlert,
  ShieldClose,
  Database,
  Globe,
  Server,
  MonitorSmartphone,
  Cpu,
  HardDrive,
  Network,
  Cloud,
} from "lucide-react";

import { cn } from "@/lib/utils";
import { AppFrame } from "@/components/layout/app-frame";
import { ClayPanel } from "@/components/layout/clay-panel";
import { GlowOrb } from "@/components/effects/glow-orb";
import { NumberTicker } from "@/components/effects/number-ticker";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from "@/components/ui/tabs";
import { PROVIDER_ICON, PROVIDER_COLOR } from "@/lib/brand-icons";

// ponytail: all mock data inline, no separate file for page-specific mocks

type Provider = "aws" | "azure" | "gcp" | "multi";
type Complexity = "simple" | "standard" | "enterprise";

const PROVIDERS: { key: Provider; label: string }[] = [
  { key: "aws", label: "AWS" },
  { key: "azure", label: "Azure" },
  { key: "gcp", label: "GCP" },
  { key: "multi", label: "Multi-Cloud" },
];

const COMPLEXITIES: { key: Complexity; label: string }[] = [
  { key: "simple", label: "Simple" },
  { key: "standard", label: "Standard" },
  { key: "enterprise", label: "Enterprise" },
];

const RECENT_GENERATIONS = [
  {
    id: "1",
    prompt: "Scalable e-commerce platform with microservices, Redis cache, and CDN",
    provider: "aws" as Provider,
    nodeCount: 12,
    timestamp: "2 hours ago",
  },
  {
    id: "2",
    prompt: "ML inference pipeline with GPU instances and auto-scaling",
    provider: "gcp" as Provider,
    nodeCount: 8,
    timestamp: "5 hours ago",
  },
  {
    id: "3",
    prompt: "Multi-region disaster recovery setup with failover",
    provider: "multi" as Provider,
    nodeCount: 16,
    timestamp: "1 day ago",
  },
  {
    id: "4",
    prompt: "Serverless API with authentication and DynamoDB",
    provider: "aws" as Provider,
    nodeCount: 6,
    timestamp: "2 days ago",
  },
];

// Architecture diagram nodes
const ARCH_NODES = [
  { id: "cdn", label: "CloudFront CDN", tier: 0, x: 50, y: 8, icon: Globe },
  { id: "lb", label: "Load Balancer", tier: 1, x: 50, y: 22, icon: Network },
  { id: "web1", label: "Web Server A", tier: 2, x: 25, y: 36, icon: MonitorSmartphone },
  { id: "web2", label: "Web Server B", tier: 2, x: 75, y: 36, icon: MonitorSmartphone },
  { id: "api", label: "API Gateway", tier: 3, x: 50, y: 50, icon: Server },
  { id: "svc1", label: "Auth Service", tier: 4, x: 20, y: 64, icon: Cpu },
  { id: "svc2", label: "Order Service", tier: 4, x: 50, y: 64, icon: Cpu },
  { id: "svc3", label: "Payment Service", tier: 4, x: 80, y: 64, icon: Cpu },
  { id: "cache", label: "Redis Cache", tier: 5, x: 25, y: 80, icon: HardDrive },
  { id: "db", label: "PostgreSQL", tier: 5, x: 55, y: 80, icon: Database },
  { id: "s3", label: "S3 Storage", tier: 5, x: 82, y: 80, icon: Cloud },
];

const ARCH_EDGES: [string, string][] = [
  ["cdn", "lb"],
  ["lb", "web1"],
  ["lb", "web2"],
  ["web1", "api"],
  ["web2", "api"],
  ["api", "svc1"],
  ["api", "svc2"],
  ["api", "svc3"],
  ["svc1", "db"],
  ["svc2", "cache"],
  ["svc2", "db"],
  ["svc3", "db"],
  ["svc3", "s3"],
];

const COST_BREAKDOWN = [
  { service: "EC2 Instances (t3.large x4)", qty: 4, unit: "$61.20", total: 244.8 },
  { service: "RDS PostgreSQL (db.r5.large)", qty: 1, unit: "$172.80", total: 172.8 },
  { service: "ElastiCache Redis (r6g.large)", qty: 1, unit: "$131.40", total: 131.4 },
  { service: "CloudFront (1TB transfer)", qty: 1, unit: "$85.00", total: 85.0 },
  { service: "S3 Storage (500GB)", qty: 1, unit: "$11.50", total: 11.5 },
  { service: "ALB (Application LB)", qty: 1, unit: "$22.27", total: 22.27 },
  { service: "NAT Gateway", qty: 2, unit: "$32.40", total: 64.8 },
  { service: "Route 53", qty: 1, unit: "$0.50", total: 0.5 },
];

const TERRAFORM_CODE = `# Generated by BlackCloud AI Architect
# Provider: AWS | Complexity: Standard

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.5.1"

  name = "ecommerce-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-east-1a", "us-east-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = false
}

resource "aws_lb" "main" {
  name               = "ecommerce-alb"
  internal           = false
  load_balancer_type = "application"
  subnets            = module.vpc.public_subnets
  security_groups    = [aws_security_group.alb.id]
}

resource "aws_instance" "web" {
  count         = 2
  ami           = data.aws_ami.amazon_linux.id
  instance_type = "t3.large"
  subnet_id     = module.vpc.private_subnets[count.index]

  tags = {
    Name = "web-server-\${count.index + 1}"
  }
}

resource "aws_db_instance" "main" {
  identifier     = "ecommerce-db"
  engine         = "postgres"
  engine_version = "15.4"
  instance_class = "db.r5.large"
  allocated_storage = 100

  db_name  = "ecommerce"
  username = "admin"

  multi_az               = true
  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.db.id]
}

resource "aws_elasticache_cluster" "redis" {
  cluster_id           = "ecommerce-cache"
  engine               = "redis"
  node_type            = "cache.r6g.large"
  num_cache_nodes      = 1
  port                 = 6379
  subnet_group_name    = aws_elasticache_subnet_group.main.name
  security_group_ids   = [aws_security_group.cache.id]
}`;

const SECURITY_FINDINGS = [
  {
    severity: "success" as const,
    title: "Encryption at Rest Enabled",
    description: "All storage services (RDS, S3, ElastiCache) have encryption at rest enabled using AWS KMS.",
    recommendation: "No action needed. Current configuration meets best practices.",
    icon: ShieldCheck,
  },
  {
    severity: "warning" as const,
    title: "Public Subnet Exposure",
    description: "Load balancer is deployed in public subnets. Ensure WAF rules are configured.",
    recommendation: "Add AWS WAF with rate limiting and geo-blocking rules to the ALB.",
    icon: ShieldAlert,
  },
  {
    severity: "destructive" as const,
    title: "Database Credentials in Plaintext",
    description: "RDS master password should not be stored in Terraform state without encryption.",
    recommendation: "Use AWS Secrets Manager and reference the secret ARN instead of plaintext credentials.",
    icon: ShieldClose,
  },
];

// ponytail: helper to look up node position by id
function nodePos(id: string) {
  const n = ARCH_NODES.find((n) => n.id === id);
  return n ? { x: n.x, y: n.y } : { x: 0, y: 0 };
}

export default function AIArchitectPage() {
  const [provider, setProvider] = useState<Provider>("aws");
  const [complexity, setComplexity] = useState<Complexity>("standard");
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasResult, setHasResult] = useState(true); // ponytail: start with results shown for demo
  const [copied, setCopied] = useState(false);

  const handleGenerate = () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setHasResult(false);
    // ponytail: fake 2.5s generation delay
    setTimeout(() => {
      setIsGenerating(false);
      setHasResult(true);
    }, 2500);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(TERRAFORM_CODE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const totalCost = COST_BREAKDOWN.reduce((s, r) => s + r.total, 0);
  const maxCost = Math.max(...COST_BREAKDOWN.map((r) => r.total));

  return (
    <AppFrame title="AI Architect">
      <div className="flex flex-col gap-6 lg:flex-row">
        {/* ===== LEFT PANEL (Prompt & Controls) ===== */}
        <div className="w-full space-y-6 lg:w-[45%]">
          {/* Header */}
          <div className="relative">
            <GlowOrb
              color="rgba(139,92,246,0.25)"
              size={200}
              className="-left-10 -top-10"
            />
            <h1 className="font-display relative text-2xl font-bold text-foreground">
              Describe your infrastructure
            </h1>
            <p className="mt-1 text-sm text-muted-foreground">
              AI will generate a complete architecture, cost estimate, and Terraform code.
            </p>
          </div>

          {/* Prompt Textarea */}
          <ClayPanel className="p-4">
            <Textarea
              rows={8}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g., I need a scalable e-commerce platform with microservices, Redis caching, PostgreSQL database, CDN for static assets, and auto-scaling web servers..."
              className="resize-none"
            />

            {/* Provider selector */}
            <div className="mt-4 space-y-3">
              <label className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                Cloud Provider
              </label>
              <div className="flex flex-wrap gap-2">
                {PROVIDERS.map((p) => {
                  const provEntry = PROVIDER_ICON[p.key];
                  const ProvIcon = provEntry?.Icon;
                  const active = provider === p.key;
                  return (
                    <button
                      key={p.key}
                      onClick={() => setProvider(p.key)}
                      className={cn(
                        "clay-card flex items-center gap-2 px-3 py-2 text-sm transition-all",
                        active
                          ? "border-primary/40 text-foreground ring-1 ring-primary/30"
                          : "text-muted-foreground hover:text-foreground"
                      )}
                    >
                      {ProvIcon && (
                        <ProvIcon
                          size={16}
                          color={active ? PROVIDER_COLOR[p.key] : undefined}
                        />
                      )}
                      {p.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Complexity selector */}
            <div className="mt-4 space-y-3">
              <label className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                Complexity
              </label>
              <div className="flex gap-2">
                {COMPLEXITIES.map((c) => {
                  const active = complexity === c.key;
                  return (
                    <button
                      key={c.key}
                      onClick={() => setComplexity(c.key)}
                      className={cn(
                        "clay-card flex-1 px-3 py-2 text-center text-sm transition-all",
                        active
                          ? "border-primary/40 text-foreground ring-1 ring-primary/30"
                          : "text-muted-foreground hover:text-foreground"
                      )}
                    >
                      {c.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Generate button */}
            <motion.button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="clay-button mt-5 flex w-full items-center justify-center gap-2 px-4 py-3 text-sm font-semibold text-foreground disabled:opacity-50"
              whileTap={{ scale: 0.98 }}
            >
              <Sparkles className="h-4 w-4" />
              {isGenerating ? "Generating..." : "Generate Architecture"}
            </motion.button>
          </ClayPanel>

          {/* Loading state */}
          <AnimatePresence>
            {isGenerating && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="clay-card flex items-center gap-3 p-4"
              >
                <div className="relative h-5 w-5">
                  <div className="absolute inset-0 animate-ping rounded-full bg-primary/40" />
                  <div className="absolute inset-0.5 rounded-full bg-primary/60" />
                </div>
                <span className="animate-pulse bg-gradient-to-r from-primary via-foreground to-primary bg-[length:200%_100%] bg-clip-text text-sm text-transparent"
                  style={{ animation: "shimmer 2s linear infinite" }}
                >
                  AI is designing your architecture...
                </span>
                <style jsx>{`
                  @keyframes shimmer {
                    0% { background-position: 200% 0; }
                    100% { background-position: -200% 0; }
                  }
                `}</style>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Recent Generations */}
          <div className="space-y-3">
            <h2 className="font-display text-lg font-semibold text-foreground">
              Recent Generations
            </h2>
            <div className="space-y-2">
              {RECENT_GENERATIONS.map((gen) => (
                <ClayPanel key={gen.id} hoverable className="p-3">
                  <p className="line-clamp-1 text-sm text-foreground">
                    {gen.prompt}
                  </p>
                  <div className="mt-2 flex items-center gap-2">
                    <Badge variant={gen.provider === "multi" ? "default" : gen.provider}>
                      {PROVIDERS.find((p) => p.key === gen.provider)?.label}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      <Layers className="mr-1 inline h-3 w-3" />
                      {gen.nodeCount} nodes
                    </span>
                    <span className="ml-auto text-xs text-muted-foreground">
                      <Clock className="mr-1 inline h-3 w-3" />
                      {gen.timestamp}
                    </span>
                  </div>
                </ClayPanel>
              ))}
            </div>
          </div>
        </div>

        {/* ===== RIGHT PANEL (Results) ===== */}
        <div className="w-full lg:w-[55%]">
          <AnimatePresence mode="wait">
            {hasResult ? (
              <motion.div
                key="results"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
              >
                <Tabs defaultValue="architecture" className="w-full">
                  <TabsList className="w-full">
                    <TabsTrigger value="architecture" className="flex-1">Architecture</TabsTrigger>
                    <TabsTrigger value="cost" className="flex-1">Cost Estimate</TabsTrigger>
                    <TabsTrigger value="terraform" className="flex-1">Terraform</TabsTrigger>
                    <TabsTrigger value="security" className="flex-1">Security</TabsTrigger>
                  </TabsList>

                  {/* ---- Architecture Tab ---- */}
                  <TabsContent value="architecture" className="mt-4">
                    <ClayPanel className="p-4">
                      <div className="mb-3 flex items-center justify-between">
                        <h3 className="font-display text-sm font-semibold text-foreground">
                          Generated Architecture
                        </h3>
                        <Badge variant="default" className="gap-1">
                          AI Confidence: 94%
                        </Badge>
                      </div>
                      <Progress value={94} className="mb-4 h-1.5" />

                      {/* SVG Architecture Diagram */}
                      <div className="clay-card relative overflow-hidden p-2">
                        <svg
                          viewBox="0 0 100 92"
                          className="h-auto w-full"
                          preserveAspectRatio="xMidYMid meet"
                        >
                          {/* Connections */}
                          {ARCH_EDGES.map(([fromId, toId]) => {
                            const from = nodePos(fromId);
                            const to = nodePos(toId);
                            return (
                              <line
                                key={`${fromId}-${toId}`}
                                x1={from.x}
                                y1={from.y + 3}
                                x2={to.x}
                                y2={to.y}
                                stroke="rgba(139,92,246,0.3)"
                                strokeWidth="0.3"
                                strokeDasharray="1,0.5"
                              />
                            );
                          })}

                          {/* Nodes */}
                          {ARCH_NODES.map((node) => (
                            <g key={node.id}>
                              {/* Node background */}
                              <rect
                                x={node.x - 9}
                                y={node.y - 2}
                                width={18}
                                height={8}
                                rx={1.5}
                                fill="rgba(22,27,34,0.9)"
                                stroke="rgba(139,92,246,0.25)"
                                strokeWidth="0.3"
                              />
                              {/* Node glow */}
                              <rect
                                x={node.x - 9}
                                y={node.y - 2}
                                width={18}
                                height={8}
                                rx={1.5}
                                fill="none"
                                stroke="rgba(139,92,246,0.1)"
                                strokeWidth="0.6"
                                filter="url(#glow)"
                              />
                              {/* Label */}
                              <text
                                x={node.x}
                                y={node.y + 3.2}
                                textAnchor="middle"
                                fill="rgba(255,255,255,0.85)"
                                fontSize="1.8"
                                fontFamily="Space Grotesk, sans-serif"
                              >
                                {node.label}
                              </text>
                            </g>
                          ))}

                          {/* Tier labels */}
                          {["CDN", "Load Balancing", "Web Tier", "API Gateway", "Services", "Data Layer"].map(
                            (label, i) => (
                              <text
                                key={label}
                                x={1}
                                y={8 + i * 14 + 2}
                                fill="rgba(139,92,246,0.3)"
                                fontSize="1.5"
                                fontFamily="JetBrains Mono, monospace"
                              >
                                {label}
                              </text>
                            )
                          )}

                          <defs>
                            <filter id="glow">
                              <feGaussianBlur stdDeviation="0.5" result="blur" />
                              <feMerge>
                                <feMergeNode in="blur" />
                                <feMergeNode in="SourceGraphic" />
                              </feMerge>
                            </filter>
                          </defs>
                        </svg>
                      </div>

                      <div className="mt-3 flex flex-wrap gap-2 text-xs text-muted-foreground">
                        <span className="clay-card px-2 py-1">11 nodes</span>
                        <span className="clay-card px-2 py-1">13 connections</span>
                        <span className="clay-card px-2 py-1">6 tiers</span>
                        <span className="clay-card px-2 py-1">Provider: AWS</span>
                      </div>
                    </ClayPanel>
                  </TabsContent>

                  {/* ---- Cost Estimate Tab ---- */}
                  <TabsContent value="cost" className="mt-4 space-y-4">
                    <ClayPanel className="p-4">
                      <h3 className="font-display mb-3 text-sm font-semibold text-foreground">
                        Monthly Cost Breakdown
                      </h3>

                      {/* Table */}
                      <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                          <thead>
                            <tr className="border-b border-white/5 text-left text-xs uppercase tracking-wider text-muted-foreground">
                              <th className="pb-2 pr-4">Service</th>
                              <th className="pb-2 pr-4 text-right">Qty</th>
                              <th className="pb-2 pr-4 text-right">Unit/mo</th>
                              <th className="pb-2 text-right">Total/mo</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-white/5">
                            {COST_BREAKDOWN.map((row) => (
                              <tr key={row.service} className="text-foreground/80">
                                <td className="py-2 pr-4 font-mono text-xs">{row.service}</td>
                                <td className="py-2 pr-4 text-right">{row.qty}</td>
                                <td className="py-2 pr-4 text-right font-mono">{row.unit}</td>
                                <td className="py-2 text-right font-mono font-semibold">
                                  ${row.total.toFixed(2)}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                          <tfoot>
                            <tr className="border-t border-primary/20 font-semibold text-foreground">
                              <td colSpan={3} className="pt-3 text-right pr-4">
                                Estimated Monthly Total
                              </td>
                              <td className="pt-3 text-right font-mono text-lg text-primary">
                                $<NumberTicker value={Math.round(totalCost)} duration={1500} />
                              </td>
                            </tr>
                          </tfoot>
                        </table>
                      </div>
                    </ClayPanel>

                    {/* Cost comparison bars */}
                    <ClayPanel className="p-4">
                      <h3 className="font-display mb-3 text-sm font-semibold text-foreground">
                        Cost Distribution
                      </h3>
                      <div className="space-y-3">
                        {COST_BREAKDOWN.map((row) => (
                          <div key={row.service}>
                            <div className="mb-1 flex justify-between text-xs">
                              <span className="text-muted-foreground">{row.service.split("(")[0].trim()}</span>
                              <span className="font-mono text-foreground">${row.total.toFixed(0)}</span>
                            </div>
                            <div className="h-2 overflow-hidden rounded-full bg-graphite/50 border border-white/5">
                              <motion.div
                                className="h-full rounded-full bg-gradient-to-r from-primary to-accent"
                                initial={{ width: 0 }}
                                animate={{ width: `${(row.total / maxCost) * 100}%` }}
                                transition={{ duration: 0.8, ease: "easeOut" }}
                              />
                            </div>
                          </div>
                        ))}
                      </div>
                    </ClayPanel>
                  </TabsContent>

                  {/* ---- Terraform Tab ---- */}
                  <TabsContent value="terraform" className="mt-4">
                    <ClayPanel className="relative p-4">
                      <div className="mb-3 flex items-center justify-between">
                        <h3 className="font-display text-sm font-semibold text-foreground">
                          Generated Terraform
                        </h3>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={handleCopy}
                          className="h-8 gap-1.5 text-xs"
                        >
                          {copied ? (
                            <Check className="h-3.5 w-3.5 text-success" />
                          ) : (
                            <Copy className="h-3.5 w-3.5" />
                          )}
                          {copied ? "Copied!" : "Copy"}
                        </Button>
                      </div>

                      <div className="clay-card overflow-auto rounded-lg bg-void p-4">
                        <pre className="font-mono text-xs leading-relaxed">
                          <code>
                            {TERRAFORM_CODE.split("\n").map((line, i) => (
                              <span key={i} className="block">
                                {/* ponytail: naive syntax coloring via prefix matching */}
                                {colorTerraformLine(line)}
                              </span>
                            ))}
                          </code>
                        </pre>
                      </div>
                    </ClayPanel>
                  </TabsContent>

                  {/* ---- Security Tab ---- */}
                  <TabsContent value="security" className="mt-4 space-y-4">
                    <ClayPanel className="p-4">
                      <div className="mb-1 flex items-center justify-between">
                        <h3 className="font-display text-sm font-semibold text-foreground">
                          Security Score
                        </h3>
                        <span className="font-mono text-2xl font-bold text-foreground">
                          <NumberTicker value={87} duration={1200} />
                          <span className="text-muted-foreground">/100</span>
                        </span>
                      </div>
                      <Progress value={87} className="h-2.5" />
                      <p className="mt-2 text-xs text-muted-foreground">
                        Your architecture scores above average. Address the critical finding below to improve.
                      </p>
                    </ClayPanel>

                    <div className="space-y-3">
                      {SECURITY_FINDINGS.map((f) => {
                        const IconComp = f.icon;
                        const badgeVariant = f.severity === "destructive" ? "destructive" : f.severity;
                        const severityLabel =
                          f.severity === "success" ? "Pass" : f.severity === "warning" ? "Warning" : "Critical";
                        return (
                          <ClayPanel key={f.title} hoverable className="p-4">
                            <div className="flex items-start gap-3">
                              <div
                                className={cn(
                                  "flex h-9 w-9 shrink-0 items-center justify-center rounded-lg",
                                  f.severity === "success" && "bg-success/15 text-success",
                                  f.severity === "warning" && "bg-warning/15 text-warning",
                                  f.severity === "destructive" && "bg-destructive/15 text-destructive"
                                )}
                              >
                                <IconComp className="h-5 w-5" />
                              </div>
                              <div className="flex-1 space-y-1">
                                <div className="flex items-center gap-2">
                                  <span className="text-sm font-semibold text-foreground">
                                    {f.title}
                                  </span>
                                  <Badge variant={badgeVariant}>{severityLabel}</Badge>
                                </div>
                                <p className="text-xs text-muted-foreground">{f.description}</p>
                                <p className="text-xs text-primary/80">
                                  <span className="font-semibold">Recommendation:</span> {f.recommendation}
                                </p>
                              </div>
                            </div>
                          </ClayPanel>
                        );
                      })}
                    </div>
                  </TabsContent>
                </Tabs>
              </motion.div>
            ) : (
              <motion.div
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex h-96 flex-col items-center justify-center text-center"
              >
                <div className="clay-card mb-4 rounded-2xl p-6">
                  <Sparkles className="mx-auto h-10 w-10 text-primary/40" />
                </div>
                <p className="text-sm text-muted-foreground">
                  Describe your infrastructure and click Generate to see results here.
                </p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </AppFrame>
  );
}

// ponytail: naive terraform syntax highlighting, no library
function colorTerraformLine(line: string): React.ReactNode {
  const trimmed = line.trimStart();
  const indent = line.length - trimmed.length;
  const pad = " ".repeat(indent);

  // Comments
  if (trimmed.startsWith("#")) {
    return <span className="text-muted-foreground italic">{pad}{trimmed}</span>;
  }

  // Resource/module/provider/terraform blocks
  const blockMatch = trimmed.match(/^(resource|module|provider|terraform|data)\s+"([^"]*)"(?:\s+"([^"]*)")?/);
  if (blockMatch) {
    return (
      <span>
        {pad}
        <span className="text-primary">{blockMatch[1]}</span>
        {" "}<span className="text-accent">&quot;{blockMatch[2]}&quot;</span>
        {blockMatch[3] && <> <span className="text-accent">&quot;{blockMatch[3]}&quot;</span></>}
        {trimmed.endsWith("{") && " {"}
      </span>
    );
  }

  // Key = "value"
  const kvMatch = trimmed.match(/^(\w+)\s*=\s*"([^"]*)"$/);
  if (kvMatch) {
    return (
      <span>
        {pad}
        <span className="text-cyan-400">{kvMatch[1]}</span>
        {" = "}
        <span className="text-emerald-400">&quot;{kvMatch[2]}&quot;</span>
      </span>
    );
  }

  // Key = value (non-string)
  const kvPlain = trimmed.match(/^(\w+)\s*=\s*(.+)$/);
  if (kvPlain) {
    return (
      <span>
        {pad}
        <span className="text-cyan-400">{kvPlain[1]}</span>
        {" = "}
        <span className="text-amber-400">{kvPlain[2]}</span>
      </span>
    );
  }

  // Closing brace or other
  return <span className="text-foreground/60">{line}</span>;
}
